# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'organizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.newItemTable = QtWidgets.QTableWidget(self.centralwidget)
        self.newItemTable.setGeometry(QtCore.QRect(10, 30, 181, 391))
        self.newItemTable.setObjectName("newItemTable")
        self.newItemTable.setColumnCount(2)
        self.newItemTable.setRowCount(0)

        self.soldItemTable = QtWidgets.QTableWidget(self.centralwidget)
        self.soldItemTable.setGeometry(QtCore.QRect(460, 30, 321, 391))
        self.soldItemTable.setObjectName("soldItemTable")
        self.soldItemTable.setColumnCount(4)
        self.soldItemTable.setRowCount(0)

        self.listedItemTable = QtWidgets.QTableWidget(self.centralwidget)
        self.listedItemTable.setGeometry(QtCore.QRect(200, 30, 251, 391))
        self.listedItemTable.setObjectName("listedItemTable")
        self.listedItemTable.setColumnCount(3)
        self.listedItemTable.setRowCount(0)

        self.selectionBox = QtWidgets.QComboBox(self.centralwidget)
        self.selectionBox.setGeometry(QtCore.QRect(370, 510, 111, 31))
        self.selectionBox.setObjectName("selectionBox")
        self.selectionBox.addItem("")
        self.selectionBox.addItem("")
        self.selectionBox.addItem("")

        self.ItemField = QtWidgets.QLineEdit(self.centralwidget)
        self.ItemField.setGeometry(QtCore.QRect(130, 510, 231, 31))
        self.ItemField.setObjectName("ItemField")

        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(670, 510, 111, 31))
        self.submitButton.setObjectName("submitButton")

        self.priceField = QtWidgets.QLineEdit(self.centralwidget)
        self.priceField.setGeometry(QtCore.QRect(490, 510, 81, 31))
        self.priceField.setObjectName("priceField")

        self.brandField = QtWidgets.QLineEdit(self.centralwidget)
        self.brandField.setGeometry(QtCore.QRect(10, 510, 113, 31))
        self.brandField.setObjectName("brandField")

        self.feesField = QtWidgets.QLineEdit(self.centralwidget)
        self.feesField.setGeometry(QtCore.QRect(580, 510, 81, 31))
        self.feesField.setObjectName("feesField")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 430, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.totalField = QtWidgets.QLabel(self.centralwidget)
        self.totalField.setGeometry(QtCore.QRect(540, 430, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.totalField.setFont(font)
        self.totalField.setText("")
        self.totalField.setObjectName("totalField")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 475, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 474, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 480, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.priceCostLabel = QtWidgets.QLabel(self.centralwidget)
        self.priceCostLabel.setGeometry(QtCore.QRect(490, 480, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.priceCostLabel.setFont(font)
        self.priceCostLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.priceCostLabel.setObjectName("priceCostLabel")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(590, 475, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(670, 430, 111, 31))
        self.deleteButton.setObjectName("deleteButton")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(590, 0, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(80, 0, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(300, 0, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.submitButton.clicked.connect(self.submit)
        
        #######-----Delete Function-----#######
        self.newItemTable.clicked.connect(lambda: self.ready(self.newItemTable.currentItem()))
        self.listedItemTable.clicked.connect(lambda: self.ready(self.listedItemTable.currentItem()))
        self.soldItemTable.clicked.connect(lambda: self.ready(self.soldItemTable.currentItem()))
        
        #######-----Combo Box Change Function------########
        self.newItemTable.doubleClicked.connect(lambda: self.ready(self.newItemTable.currentItem()))
        self.listedItemTable.doubleClicked.connect(lambda: self.ready(self.listedItemTable.currentItem()))
        
        


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Organizer"))
        self.selectionBox.setItemText(0, _translate("MainWindow", "New"))
        self.selectionBox.setItemText(1, _translate("MainWindow", "Listed"))
        self.selectionBox.setItemText(2, _translate("MainWindow", "Sold"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "Total:"))
        self.label_3.setText(_translate("MainWindow", "Brand (opt)"))
        self.label_4.setText(_translate("MainWindow", "Item"))
        self.label_5.setText(_translate("MainWindow", "Position"))
        self.priceCostLabel.setText(_translate("MainWindow", "Price"))
        self.label_7.setText(_translate("MainWindow", "Extra Fees"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.label_8.setText(_translate("MainWindow", "Sold"))
        self.label_9.setText(_translate("MainWindow", "New"))
        self.label_10.setText(_translate("MainWindow", "Listed"))

    def submit(self):
        if self.selectionBox.currentText() == "New":
            self.newItemTable.insertRow(self.newItemTable.rowCount())
            brand = self.brandField.text()
            item = self.ItemField.text()
            self.newItemTable.setItem(self.newItemTable.rowCount()-1, 0, QtWidgets.QTableWidgetItem(brand))
            self.newItemTable.setItem(self.newItemTable.rowCount()-1, 1, QtWidgets.QTableWidgetItem(item))
            self.brandField.clear()
            self.ItemField.clear()
        elif self.selectionBox.currentText() == "Listed":
            self.listedItemTable.insertRow(self.listedItemTable.rowCount())
            brand = self.brandField.text()
            item = self.ItemField.text()
            price = self.priceField.text()
            self.listedItemTable.setItem(self.listedItemTable.rowCount()-1, 0, QtWidgets.QTableWidgetItem(brand))
            self.listedItemTable.setItem(self.listedItemTable.rowCount()-1, 1, QtWidgets.QTableWidgetItem(item))
            self.listedItemTable.setItem(self.listedItemTable.rowCount()-1, 2, QtWidgets.QTableWidgetItem(price))
            self.brandField.clear()
            self.ItemField.clear()
            self.priceField.clear()
        elif self.selectionBox.currentText() == "Sold":
            self.soldItemTable.insertRow(self.soldItemTable.rowCount())
            brand = self.brandField.text()
            item = self.ItemField.text()
            price = self.priceField.text()
            fees = self.feesField.text()
            self.soldItemTable.setItem(self.soldItemTable.rowCount()-1, 0, QtWidgets.QTableWidgetItem(brand))
            self.soldItemTable.setItem(self.soldItemTable.rowCount()-1, 1, QtWidgets.QTableWidgetItem(item))
            self.soldItemTable.setItem(self.soldItemTable.rowCount()-1, 2, QtWidgets.QTableWidgetItem(price))
            self.soldItemTable.setItem(self.soldItemTable.rowCount()-1, 3, QtWidgets.QTableWidgetItem(fees))
            self.brandField.clear()
            self.ItemField.clear()
            self.priceField.clear()
            self.feesField.clear()

    
    def ready(self, item):
        table = item.tableWidget()
        #table.setCurrentItem(item)
        tableName = item.tableWidget().objectName()
        row = item.tableWidget().currentRow()

        if tableName == "newItemTable":
            self.brandField.setText(table.item(row, 0).text())
            self.ItemField.setText(table.item(row, 1).text())
            
        elif tableName == "listedItemTable":
            self.brandField.setText(table.item(row, 0).text())
            self.ItemField.setText(table.item(row, 1).text())
            self.priceField.setText(table.item(row, 2).text())
            

        self.deleteButton.clicked.connect(lambda: self.delete(item))
   
    

    def delete(self, event):
        #print(event.tableWidget().objectName())
        table = event.tableWidget()
        table.removeRow(table.currentRow())
        self.brandField.clear()
        self.ItemField.clear()
        self.priceField.clear()
        self.feesField.clear()
        self.deleteButton.clicked.disconnect()

    #def change(self, item):
    #    table = item.tableWidget()
    #    #table.setCurrentItem(item)
    #    tableName = item.tableWidget().objectName()
    #    row = item.tableWidget().currentRow()
#
    #    if tableName == "newItemTable":
    #        self.brandField.setText(table.item(row, 0).text())
    #        self.ItemField.setText(table.item(row, 1).text())
    #        table.item(row, 0)
    #    elif tableName == "listedItemTable":
    #        self.brandField.setText(table.item(row, 0).text())
    #        self.ItemField.setText(table.item(row, 1).text())
    #        self.priceField.setText(table.item(row, 2).text())
    #        table.removeRow(row)

    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
